lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
nf_core_version: 3.4.1
repository_type: pipeline
template:
  author: Jannik Seidel
  description: A pipeline to identify (and remove) certain sequences from raw genomic data. Default taxon to identify (and remove) is Homo sapiens. Removal is optional.
  force: false
  is_nfcore: true
  name: detaxizer
  org: nf-core
  outdir: .
  version: 1.3.0
