lint:
  files_unchanged:
    - .gitignore
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
    - assets/nf-core-detaxizer_logo_light.png
    - docs/images/nf-core-detaxizer_logo_light.png
    - docs/images/nf-core-detaxizer_logo_dark.png
  files_exist:
    - .github/workflows/linting_comment.yml
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: Jannik Seidel
  description: A pipeline to identify (and remove) certain sequences from raw genomic data. Default taxon to identify (and remove) is Homo sapiens. Removal is optional.
  force: false
  is_nfcore: true
  name: detaxizer
  org: nf-core
  outdir: .
  version: 1.4.0dev
